package com.myspace.claimsconnect_rulesbase;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class slaResult implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "escalateTo")
	private java.lang.String escalateTo;
	@org.kie.api.definition.type.Label(value = "escalationType")
	private java.lang.String escalationType;
	@org.kie.api.definition.type.Label(value = "duration")
	private java.lang.String duration;

	public slaResult() {
	}

	public java.lang.String getEscalateTo() {
		return this.escalateTo;
	}

	public void setEscalateTo(java.lang.String escalateTo) {
		this.escalateTo = escalateTo;
	}

	public java.lang.String getEscalationType() {
		return this.escalationType;
	}

	public void setEscalationType(java.lang.String escalationType) {
		this.escalationType = escalationType;
	}

	public java.lang.String getDuration() {
		return this.duration;
	}

	public void setDuration(java.lang.String duration) {
		this.duration = duration;
	}

	public slaResult(java.lang.String escalateTo,
			java.lang.String escalationType, java.lang.String duration) {
		this.escalateTo = escalateTo;
		this.escalationType = escalationType;
		this.duration = duration;
	}

}