package com.myspace.claimsconnect_rulesbase;
import com.myspace.claimsconnect_rulesbase.slaObject;
import com.myspace.claimsconnect_rulesbase.slaResult;
import java.util.ArrayList;
import java.util.List;

ruleflow-group "slaDRL"
rule "duration"
when
$slaObject:slaObject(slaObject.claimType=="Life" && slaObject.persona=="RINOPR")

$a:  ArrayList()  
              from collect( com.myspace.claimsconnect_rulesbase.slaResult( ) from $slaObject.getSlaResult()) 
then
System.out.println("Frontend");
$a.add(new com.myspace.claimsconnect_rulesbase.slaResult("24h","RINOPR","Self Reminder"));
System.out.println("Triggered"+$a);
$slaObject.setSlaResult($a);
$a.add(new com.myspace.claimsconnect_rulesbase.slaResult("48h","RINOPR","Escalation"));
System.out.println("Triggered"+$a);
$slaObject.setSlaResult($a);
end;

